image: itzg/minecraft-server
imageTag: multiarch-latest
#imageTag: multiarch

resources:
  requests:
    memory: 4Gi
    cpu: 500m
  limits:
    memory: 5Gi
    cpu: 1

minecraftServer:
  # kube options
  serviceType: LoadBalancer
  loadBalancerIP: 192.168.0.113

  # minecraft options
  memory: 4096M
  eula: "TRUE"
  type: "FTBA"
  ftbServerMod: https://api.modpacks.ch/public/modpack/25/123/server/linux  # skyfactory3
  difficulty: hard
  maxPlayers: 10
  pvp: true

  # performance improvements
  viewDistance: 6
  maxWorldSize: 8000

  # players
  # whitelist:
  
  # rcon
  #rcon:
  #  enabled: true
  #  port: 25575
  #  password: "rcon_pass"
  #  serviceType: LoadBalancer
  #  loadBalancerIP: 192.168.0.113

extraEnv:
#  FTB_MODPACK_ID: 35 # revelation
  FTB_MODPACK_ID: 25 # skyfactory3
