---
persistentVolumeClaim:
  enabled: true

serviceWeb:
  loadBalancerIP: 192.168.0.130
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceDns:
  loadBalancerIP: 192.168.0.130
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

adminPassword: password
virtualHost: pihole.service.homelab
