image: itzg/minecraft-server
imageTag: multiarch-latest
#imageTag: multiarch

securityContext:
  runAsUser: 1000
  fsGroup: 1000

resources:
  requests:
    memory: 4Gi
    cpu: 500m
  limits:
    memory: 5Gi
    cpu: 1

livenessProbe:
  initialDelaySeconds: 1800
  periodSeconds: 10
  failureThreshold: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  initialDelaySeconds: 1800
  periodSeconds: 10
  failureThreshold: 20
  successThreshold: 1
  timeoutSeconds: 1

minecraftServer:
  # kube options
  serviceType: LoadBalancer
  loadBalancerIP: 192.168.0.112

  # minecraft options
  memory: 4096M
  eula: "TRUE"
  difficulty: hard
  maxPlayers: 10
  pvp: true

  # performance improvements
  viewDistance: 6
  maxWorldSize: 8000

  # players
  # whitelist:
  
  # rcon
  #rcon:
  #  enabled: true
  #  port: 25575
  #  password: "rcon_pass"
  #  serviceType: LoadBalancer
  #  loadBalancerIP: 192.168.0.113

