---
- hosts: cluster
  become: true
  tasks:
    # fix /boot/firmware/cmdline.txt first
    - name: enable cgroup features
      lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: True
        regexp: '(^.+rootwait(\s+(?!cgroup_enable=memory cgroup_memory=1)[\w=/\-\.]+)*)\s*$'
        line: '\1 cgroup_enable=memory cgroup_memory=1'
        state: present

    - name: install microk8s
      snap:
        name: microk8s
        classic: yes
