---
- hosts: cluster
  become: true
  tasks:
    - name: install nfs tools
      apt:
        name: libnfs-utils
        state: present
    - name: install nfs storage mount helper
      apt:
        name: nfs-common
        state: present
